export const UNITS = [
  // === PHƯỜNG ===
  "Công an phường An Tường",
  "Công an phường Bình Thuận",
  "Công an phường Hà Giang 1",
  "Công an phường Hà Giang 2",
  "Công an phường Minh Xuân",
  "Công an phường Mỹ Lâm",
  "Công an phường Nông Tiến",

  // === XÃ (A - B) ===
  "Công an xã Bắc Mê",
  "Công an xã Bắc Quang",
  "Công an xã Bạch Đích",
  "Công an xã Bạch Ngọc",
  "Công an xã Bạch Xa",
  "Công an xã Bản Máy",
  "Công an xã Bằng Hành",
  "Công an xã Bằng Lang",
  "Công an xã Bình An",
  "Công an xã Bình Ca",
  "Công an xã Bình Xa",

  // === XÃ (C - Đ) ===
  "Công an xã Cán Tỷ",
  "Công an xã Cao Bồ",
  "Công an xã Chiêm Hóa",
  "Công an xã Côn Lôn",
  "Công an xã Đồng Tâm",
  "Công an xã Đông Thọ",
  "Công an xã Đồng Văn",
  "Công an xã Đồng Yên",
  "Công an xã Du Già",
  "Công an xã Đường Hồng",
  "Công an xã Đường Thượng",

  // === XÃ (G - H) ===
  "Công an xã Giáp Trung",
  "Công an xã Hàm Yên",
  "Công an xã Hồ Thầu",
  "Công an xã Hòa An",
  "Công an xã Hoàng Su Phì",
  "Công an xã Hồng Sơn",
  "Công an xã Hồng Thái",
  "Công an xã Hùng An",
  "Công an xã Hùng Đức",
  "Công an xã Hùng Lợi",

  // === XÃ (K - L) ===
  "Công an xã Khâu Vai",
  "Công an xã Khuôn Lùng",
  "Công an xã Kiên Đài",
  "Công an xã Kiến Thiết",
  "Công an xã Kim Bình",
  "Công an xã Lâm Bình",
  "Công an xã Lao Chải",
  "Công an xã Liên Hiệp",
  "Công an xã Linh Hồ",
  "Công an xã Lực Hành",
  "Công an xã Lũng Cú",
  "Công an xã Lũng Phìn",
  "Công an xã Lùng Tám",

  // === XÃ (M - N) ===
  "Công an xã Mậu Duệ",
  "Công an xã Mèo Vạc",
  "Công an xã Minh Ngọc",
  "Công an xã Minh Quang",
  "Công an xã Minh Sơn",
  "Công an xã Minh Tân",
  "Công an xã Minh Thanh",
  "Công an xã Nà Hang",
  "Công an xã Nấm Dẩn",
  "Công an xã Nậm Dịch",
  "Công an xã Nghĩa Thuận",
  "Công an xã Ngọc Đường",
  "Công an xã Ngọc Long",
  "Công an xã Nhữ Khê",
  "Công an xã Niêm Sơn",

  // === XÃ (P - Q) ===
  "Công an xã Pà Vầy Sủ",
  "Công an xã Phố Bảng",
  "Công an xã Phú Linh",
  "Công an xã Phú Lương",
  "Công an xã Phù Lưu",
  "Công an xã Pờ Ly Ngài",
  "Công an xã Quản Bạ",
  "Công an xã Quang Bình",
  "Công an xã Quảng Nguyên",

  // === XÃ (S) ===
  "Công an xã Sà Phìn",
  "Công an xã Sơn Dương",
  "Công an xã Sơn Thủy",
  "Công an xã Sơn Vĩ",
  "Công an xã Sủng Máng",

  // === XÃ (T) ===
  "Công an xã Tân An",
  "Công an xã Tân Long",
  "Công an xã Tân Mỹ",
  "Công an xã Tân Quang",
  "Công an xã Tân Thanh",
  "Công an xã Tân Tiến",
  "Công an xã Tân Trào",
  "Công an xã Tân Trịnh",
  "Công an xã Tát Ngà",
  "Công an xã Thái Bình",
  "Công an xã Thái Hòa",
  "Công an xã Thái Sơn",
  "Công an xã Thắng Mố",
  "Công an xã Thàng Tín",
  "Công an xã Thanh Thủy",
  "Công an xã Thông Nguyên",
  "Công an xã Thuận Hòa",
  "Công an xã Thượng Lâm",
  "Công an xã Thượng Nông",
  "Công an xã Thượng Sơn",
  "Công an xã Tiên Nguyên",
  "Công an xã Tiên Yên",
  "Công an xã Tri Phú",
  "Công an xã Trung Hà",
  "Công an xã Trung Sơn",
  "Công an xã Trung Thịnh",
  "Công an xã Trường Sinh",
  "Công an xã Tùng Bá",
  "Công an xã Tùng Vài",

  // === XÃ (V - X - Y) ===
  "Công an xã Vị Xuyên",
  "Công an xã Việt Lâm",
  "Công an xã Vĩnh Tuy",
  "Công an xã Xín Mần",
  "Công an xã Xuân Giang",
  "Công an xã Xuân Vân",
  "Công an xã Yên Cường",
  "Công an xã Yên Hoa",
  "Công an xã Yên Lập",
  "Công an xã Yên Minh",
  "Công an xã Yên Nguyên",
  "Công an xã Yên Phú",
  "Công an xã Yên Sơn",
  "Công an xã Yên Thành",

  // === ĐƠN VỊ NGHIỆP VỤ ===
  "PK02",
  "TTGS1",
  "TTGS2",
  "PC07",
  "PC10"
];

export const FITNESS_FIELDS = [
  { id: 'run100', label: 'Chạy 100m' },
  { id: 'run800', label: 'Chạy 800m' },
  { id: 'run1500', label: 'Chạy 1.500m' },
  { id: 'pullUp', label: 'Co tay xà đơn' },
  { id: 'longJump', label: 'Bật xa' }
];
